### ISSUE TITLE
ffmpeg no generate gif?

### ISSUE THREAD

**Issue by yun013** [Scheliux/mpv-gif-generator#1]
when i make de combination "ctrl+g", only appear quickly the cmd and disappeared, and not found the gif generated. i think is the ffmpeg.exe location.

**Comment by Scheliux** [comment]
The ffmpeg.exe file has to be located in the mpv's folder next to the mpv.exe file. If everything goes well you will find the gif in the opened video's directory.

**Comment by yun013** [comment]
I tried locate the ffmpeg.exe in the same place of the mpv.exe, also 
the ffmpeg.exe in Scripts folder. I no find gif generated in the video directory.

**Comment by Scheliux** [comment]
You have to put mpv directory into system variables. Otherwise it will not recognize the mpv and ffmpeg. You can do it by following these steps.

![](https://i.imgur.com/6MFBV4S.png)

Now open command prompt, type "mpv", and if you get something like this it has to work from now.

![](https://i.imgur.com/zApkOPE.png)

**Comment by yun013** [comment]
Thank's, now Works 👍 .
